CREATE TABLE IF NOT EXISTS ARTIST(
    ID SERIAL PRIMARY KEY ,
    NAME varchar(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
    ID SERIAL PRIMARY KEY,
    NAME varchar(256) NOT NULL,
    TYPE varchar(256),
    ARTIST_ID INTEGER NOT NULL,
    CONSTRAINT ARTIST_ID_FK FOREIGN KEY (ARTIST_ID) REFERENCES artist (ID)
);

CREATE TABLE IF NOT EXISTS TRACK(
    ID SERIAL PRIMARY KEY,
    NAME varchar(256) NOT NULL,
    TIME INTEGER NOT NULL,
    ALBUM_ID INTEGER NOT NULL,
    CONSTRAINT ALBUM_ID_FK FOREIGN KEY (ALBUM_ID) REFERENCES album (ID)
);


